# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PlxWmm58xvnZYfPiEmRb6raCG0yQtVcJ
"""

import matplotlib.pyplot as plt

import numpy as np

x=np.array([1,2,3,4,5,6])
y=np.array([6,6,6,6,6,6])
x1=np.array([3,3,3,3,3,3])
y1=np.array([5,6,5.8,5.6,5.4,5.2])
mycolor=['red','green','purple','lime','aqua','yellow']
plt.scatter(x,y,color=mycolor)
plt.scatter(x1,y1,color=mycolor)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['60-24','61-24','631-A'])
y=np.array([16,19,11])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([5,4,5,5,4])
mylabels=["KB","SI","EvS","DT","CHA"]
plt.pie(x,labels=mylabels)
plt.show()

